<?php
/**
 * Created by PhpStorm.
 * User: M
 * Date: 17/6/20
 * Time: 下午5:02
 */

namespace app\controllers;

use Yii;

class Controller extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        if(Yii::$app->user->isGuest){
            Yii::$app->end(Yii::$app->response->exitStatus, $this->redirect(['site/login']));
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}